# 第 13 章成绩统计
虚构教学数据。每行一名学生，三列依次为 Python、数据处理、AI 基础。

In [1]:
import numpy as np
from examples.score_stats import SCORES, STUDENTS, SUBJECTS, summarize
print('NumPy', np.__version__)
print(STUDENTS)
print(SUBJECTS)
print(SCORES)

NumPy 2.3.5
['小林', '小周', '小陈', '小吴']
['Python', '数据处理', 'AI 基础']
[[80. 70. 90.]
 [60. 85. 75.]
 [95. 90. 85.]
 [50. 60. 70.]]


## 形状与索引
数组的第 0 轴对应学生，第 1 轴对应课程。

In [2]:
print('shape', SCORES.shape)
print('ndim', SCORES.ndim)
print('size', SCORES.size)
print('小周的 AI 基础', SCORES[1, 2])
print('Python 列', SCORES[:, 0])

shape (4, 3)
ndim 2
size 12
小周的 AI 基础 75.0
Python 列 [80. 60. 95. 50.]


## 分别汇总学生和课程
axis 参数决定汇总哪个方向。

In [3]:
result = summarize(SCORES)
print('学生均分', result['student_means'])
print('课程均分', result['subject_means'])
print('整体均分', result['overall_mean'])
print('批量与循环一致', np.allclose(result['student_means'], result['loop_means']))

学生均分 [80.0, 73.33333333333333, 90.0, 60.0]
课程均分 [71.25, 76.25, 80.0]
整体均分 75.83333333333333
批量与循环一致 True


In [4]:
bonus = np.array([5, 0, 2])
print('调整成绩', np.minimum(SCORES + bonus, 100))
mask = (SCORES >= 60).all(axis=1)
print('全部及格', np.array(STUDENTS)[mask])

调整成绩 [[ 85.  70.  92.]
 [ 65.  85.  77.]
 [100.  90.  87.]
 [ 55.  60.  72.]]
全部及格 ['小林' '小周' '小陈']


## 独立练习
先纸面确认小周和小陈的两门指定课程，再运行。

In [5]:
selected = SCORES[1:3, ::2]
print(selected)
print(selected.shape)
print(selected.mean(axis=1))
np.testing.assert_allclose(selected.mean(axis=1), [67.5, 90])

[[60. 75.]
 [95. 85.]]
(2, 2)
[67.5 90. ]
